plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url = "https://maven.architectury.dev/" }
	maven { url = "https://maven.shedaniel.me/" }
	mavenCentral()
	maven { url = "https://maven.terraformersmc.com/" }

}

loom {
	runs {
		datagen {
			inherit server
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
			vmArg "-Dfabric-api.datagen.modid=keybindsgalore"
			runDir "build/datagen"
		}
	}
}

sourceSets {
	main {
		resources {
			srcDirs += ['src/main/generated']
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "it.unimi.dsi:fastutil:8.5.12"

	// --- Cloth Config & ModMenu ---
	implementation ("me.shedaniel.cloth:cloth-config-fabric:26.1.154") {
		exclude group: 'net.fabricmc.fabric-api'
	}
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
	repositories {
		// Add publishing target if needed (e.g., Modrinth/Maven/etc)
	}
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs += ["-Xlint:deprecation", "-Xlint:unchecked"]
}
