# Gradle JVM Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop

# --- Mod Identity (Refactored) ---
mod_version=1.7.2+1.21.11
maven_group=net.hvb007
archives_base_name=keybindsgalore

# --- Dependencies (1.21.11) ---
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.19.3

# Fabric API
fabric_version=0.141.4+1.21.11

# owo-lib
owo_version=0.13.0+1.21.11

org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.9.10-hotspot

