org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.8.0+26.3
maven_group=net.hvb007
archives_base_name=keybindsgalore

minecraft_version=26.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.161.0+26.3
cloth_version=26.3.159
modmenu_version=21.0.0

